WebLB2/Controllers/LB2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LB2.Models;
using LB2.Models.ViewModels;
using System.Security.Cryptography;
using System.Web.Security;
using System.Security.Principal;
using System.Text;

namespace WebLB2.Controllers
{
    public class LB2Controller : Controller
    {
        [AllowAnonymous]
        public ActionResult ListOfStudents()
        {
            List<Студенты> students = new List<Студенты>();
            using( var db= new VMamontovEntities())
            {
             
                students = db.Студенты.OrderByDescending(x => x.Имя)
                    .ThenBy(x => x.Фамилия).ToList();
               
            }
            return View(students);
        }
        [Authorize]
        public ActionResult StudentDetails(Guid personId)
        {
            Студенты model = new Студенты();
            using (var db = new VMamontovEntities())
            {
                model = db.Студенты.Find(personId);
            }
                return View(model);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        [HttpGet]
        [Authorize(Roles ="Admin")]
        public ActionResult CreateStudent()
        {
            ViewBag.Genders = new SelectList(GetGenderList(), "Item1", "Item2");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult CreateStudent(Студенты newStudent)
        {
            if (ModelState.IsValid)
            {
                using (var context = new VMamontovEntities())
                {
                    Студенты студент = new Студенты
                    {
                        ID_студента = Guid.NewGuid(),
                        Фамилия = newStudent.Фамилия,
                        Имя= newStudent.Имя,
                        Отчество = newStudent.Отчество,
                        Пол= newStudent.Пол,
                        Адрес_проживания= newStudent.Адрес_проживания,
                        Дата_рождения= newStudent.Дата_рождения,
                        Уровень_владения_ИЯ= newStudent.Уровень_владения_ИЯ,
                        InsertedDateTime = newStudent.InsertedDateTime,
                        WakeUpTime = newStudent.WakeUpTime,
                        GraduationDate = newStudent.GraduationDate
                    };
                    context.Студенты.Add(студент);
                    context.SaveChanges();
             
                    
                }
                return RedirectToAction("ListOfStudents");
            }
            ViewBag.Genders = new SelectList(GetGenderList(), "Item1", "Item2");
            return View(newStudent);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult EditStudent(Guid studentID)
        {
            Студенты model;
            using (var context = new VMamontovEntities())
            {
                Студенты student = context.Студенты.Find(studentID);
                model = new Студенты
                {
                    ID_студента = student.ID_студента,
                    Фамилия = student.Фамилия,
                    Имя = student.Имя,
                    Отчество = student.Отчество,
                    Пол = student.Пол,
                    Адрес_проживания = student.Адрес_проживания,
                    Дата_рождения = student.Дата_рождения,
                    Уровень_владения_ИЯ = student.Уровень_владения_ИЯ,
                    InsertedDateTime = student.InsertedDateTime,
                    WakeUpTime = student.WakeUpTime,
                    GraduationDate = student.GraduationDate
                };

            }
            ViewBag.Genders = new SelectList(GetGenderList(), "Item1", "Item2");
            return View(model);
        }


        [HttpPost]
        public ActionResult EditStudent(Студенты newStudent)
        {
            if (ModelState.IsValid)
            {
                using (var context = new VMamontovEntities())
                {
                    Студенты студент = new Студенты
                    {
                        ID_студента = newStudent.ID_студента,
                        Фамилия = newStudent.Фамилия,
                        Имя = newStudent.Имя,
                        Отчество = newStudent.Отчество,
                        Пол = newStudent.Пол,
                        Адрес_проживания = newStudent.Адрес_проживания,
                        Дата_рождения = newStudent.Дата_рождения,
                        Уровень_владения_ИЯ = newStudent.Уровень_владения_ИЯ,
                            InsertedDateTime = newStudent.InsertedDateTime,
                        WakeUpTime = newStudent.WakeUpTime,
                        GraduationDate = newStudent.GraduationDate
                    };
                    context.Студенты.Attach(студент);
                    context.Entry(студент).State = System.Data.Entity.EntityState.Modified;
                    context.SaveChanges();


                }
                return RedirectToAction("ListOfStudents");
            }
            ViewBag.Genders = new SelectList(GetGenderList(), "Item1", "Item2");
            return View(newStudent);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteStudent(Guid studentID)
        {
            Студенты deleteStudent;
            using (var context = new VMamontovEntities())
            {
                deleteStudent = context.Студенты.Find(studentID);
            }
            return View(deleteStudent);
            }
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(UserVM webUser)
        {
            if (ModelState.IsValid)
            {
                using (var context = new VMamontovEntities())
                {
                    User user = null;
                    user = context.User.Where(u => u.Login == webUser.Login).FirstOrDefault();
                    if (user != null)
                    {
                        string PasswordHash = ReturnHashCode(webUser.Password + user.Salt.ToString().ToUpper());
                        if (PasswordHash == user.PasswordHash)
                        {
                            string userRole = "";
                            switch (user.UserRole)
                            {
                                case 2:
                                    userRole = "User";
                                    break;
                                case 3:
                                    userRole = "Admin";
                                    break;
                            }
                            FormsAuthenticationTicket authTicket = new FormsAuthenticationTicket(
                                1, user.Login, DateTime.Now, DateTime.Now.AddDays(1), false, userRole);
                            string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                            HttpContext.Response.Cookies.Add(new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket));
                            return RedirectToAction("ListOfStudents");
                        }
                    }
                }
            }
            ViewBag.Error = "Пользователя с таким логином и паролем не существует, попробуйте ещё";
            return View(webUser);
            }
        string ReturnHashCode(string LoginAndSalt)
        {
            string hash = "";
            using (SHA1 sha1Hash = SHA1.Create())
            {
                byte[] data = sha1Hash.ComputeHash(Encoding.UTF8.GetBytes(LoginAndSalt));
                StringBuilder sBuilder = new StringBuilder();
                for (int i=0; i<data.Length; i++)
                {
                    sBuilder.Append(data[i].ToString("x2"));
                }
                hash = sBuilder.ToString().ToUpper();
            }
            return hash;
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("ListOfStudents");
        }
        [HttpPost, ActionName("DeleteStudent")]
        public ActionResult DeleteConfirmed(Guid studentID)
        {
            Студенты deleteStudent;
            using (var context = new VMamontovEntities())
            {
                deleteStudent = context.Студенты.Find(studentID);
                context.Студенты.Remove(deleteStudent);
                context.SaveChanges();
            }
            return RedirectToAction("ListOfStudents");
            }
        [ChildActionOnly]
        public ActionResult GraduationDate(Guid studentID)
        {
            string message = "";
            using (var context = new VMamontovEntities())
            {
                string graduationDate = context.Студенты.Find(studentID).GraduationDate.ToString();
                message = "Дата выпуска: " + graduationDate;
            }
            return PartialView("", message);
            }
        [ValidateAntiForgeryToken]
        List<Tuple<bool,string>> GetGenderList()
        {
            List<Tuple<bool, string>> genders = new List<Tuple<bool, string>>
            {
                new Tuple<bool, string>(false,"Женский"),
                new Tuple<bool, string>(true,"Мужской"),
            };
            return genders;
        }
    }
}

WebLB2/Views/LB2/CreateStudent.cshtml
@model LB2.Models.Студенты

@{
    ViewBag.Title = "CreateStudent";
}

<h2>CreateStudent</h2>

@using (Html.BeginForm("CreateStudent", "LB2", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Студенты</h4>
    <hr />
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Фамилия, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Фамилия, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Фамилия, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Имя, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Имя, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Имя, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Отчество, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Отчество, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Отчество, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Пол, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Пол,
           ViewBag.Genders as SelectList, "---", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Пол, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Адрес_проживания, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Адрес_проживания, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Адрес_проживания, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Дата_рождения, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Дата_рождения, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Дата_рождения, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Уровень_владения_ИЯ, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Уровень_владения_ИЯ, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Уровень_владения_ИЯ, "", new { @class = "text-danger" })
        </div>
    </div>
 
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ListOfStudents")
  
</div>

WebLB2/Views/LB2/DeleteStudent.cshtml
@model LB2.Models.Студенты

@{
    ViewBag.Title = "DeleteStudent";
}

<h2>DeleteStudent</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Студенты</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Фамилия)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Фамилия)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Имя)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Имя)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Отчество)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Отчество)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Пол)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Пол)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Адрес_проживания)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Адрес_проживания)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Дата_рождения)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_рождения)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Уровень_владения_ИЯ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Уровень_владения_ИЯ)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ListOfStudents")
        </div>
    }
</div>

WebLB2/Views/LB2/EditStudent.cshtml
@model LB2.Models.Студенты

@{
    ViewBag.Title = "EditStudent";
}

<h2>EditStudent</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Студенты</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_студента)

    <div class="form-group">
        @Html.LabelFor(model => model.Фамилия, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Фамилия, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Фамилия, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Имя, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Имя, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Имя, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Отчество, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Отчество, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Отчество, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Пол, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Пол)
                @Html.ValidationMessageFor(model => model.Пол, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Адрес_проживания, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Адрес_проживания, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Адрес_проживания, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Дата_рождения, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Дата_рождения, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Дата_рождения, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Уровень_владения_ИЯ, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Уровень_владения_ИЯ, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Уровень_владения_ИЯ, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.InsertedDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.InsertedDateTime, "0: yyyy-MM-ddThh: mm", new { @class = "form-control", type = "datetime-local" })
            @Html.ValidationMessageFor(model => model.InsertedDateTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.WakeUpTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.WakeUpTime, "0: HH: mm: ss", new { @class = "form-control", type = "time" })
            @Html.ValidationMessageFor(model => model.WakeUpTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GraduationDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.GraduationDate, "0: yyyy-MM-dd", new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.GraduationDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ListOfStudents")
</div>

WebLB2/Views/LB2/GraduationDate.cshtml
@model string
<i>@Model</i>

WebLB2/Views/LB2/ListOfStudents.cshtml
@model List<LB2.Models.Студенты>
@{ 
    ViewBag.Title = "ListOfStudents";
}
<h2>Отсортированный список участников опроса (таблица)</h2>
@Html.ActionLink("Добавить студента","CreateStudent", "LB2", new { @class = "btn btn-default"})

<div class="row">
    <div class="col-md-4"><strong>Наименование</strong></div>
    <div class="col-md-2"><strong>Возраст</strong></div>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="col-md-2"><strong>#</strong></div>
        if (User.IsInRole("Admin"))
        {
            <div class="col-md-2"><strong>#</strong></div>
            <div class="col-md-2"><strong>#</strong></div>
        }
    }


</div>
        @foreach (var student in Model)
        {
       
            @Html.Partial("StudentOverviewPartial",student)
        }
 

WebLB2/Views/LB2/Login.cshtml
@model LB2.Models.ViewModels.UserVM

@{
    ViewBag.Title = "SignUpView";
}

<h2>SignUpView</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type="password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Войти" class="btn btn-default" />
            </div>
            <p>
                @if (!String.IsNullOrEmpty(ViewBag.Error))
                {
                    @Html.Label((string)(ViewBag.Error), new  { @class = "alert alert-danger"})
                }
            </p>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListOfStudents")
</div>

WebLB2/Views/LB2/StudentDetails.cshtml
@model LB2.Models.Студенты

@{
    ViewBag.Title = "StudentDetails";
}

<h2>Участник опроса</h2>
<h4>Студенты</h4>
<hr />
<div>

    <dl class="row">
        <div class="col-md-1"> @Html.LabelFor(m => m.Фамилия)</div>
        <div class="col-md-3"> @Html.DisplayFor(m => m.Фамилия)</div>
    </dl>
    <dl class="row">
        <div class="col-md-1"> @Html.LabelFor(m => m.Имя)</div>
        <div class="col-md-3"> @Html.DisplayFor(m => m.Имя)</div>
    </dl>
    <dl class="row">
        <div class="col-md-1"> @Html.LabelFor(m => m.Отчество)</div>
        <div class="col-md-3"> @Html.DisplayFor(m => m.Отчество)</div>
    </dl>
    <dl class="row">
        <div class="col-md-1"> @Html.LabelFor(m => m.Дата_рождения)</div>
        <div class="col-md-3"> @Html.DisplayFor(m => m.Дата_рождения)</div>
    </dl>
    <dl class="row">
        <div class="col-md-2"> @Html.LabelFor(m => m.Адрес_проживания)</div>
        <div class="col-md-10"> @Html.DisplayFor(m => m.Адрес_проживания)</div>
    </dl>
    <dl class="row">
        <div class="col-md-1"> @Html.LabelFor(m => m.Пол)</div>
        <div class="col-md-3"> @Html.DisplayFor(m => m.Пол)</div>
    </dl>
    <dl class="row">
        <div class="col-md-1"> @Html.LabelFor(m => m.InsertedDateTime)</div>
        <div class="col-md-3"> @Html.DisplayFor(m => m.InsertedDateTime)</div>
    </dl>
    <dl class="row">
        <div class="col-md-1"> @Html.LabelFor(m => m.WakeUpTime)</div>
        <div class="col-md-3"> @Html.DisplayFor(m => m.WakeUpTime)</div>
    </dl>
    <dl class="row">
        <div class="col-md-1"> @Html.LabelFor(m => m.GraduationDate)</div>
        <div class="col-md-3"> @Html.DisplayFor(m => m.GraduationDate)</div>
    </dl>
</div>

    <p>
        @Html.ActionLink("Назад", "ListOfStudents")
    </p>

WebLB2/Views/LB2/StudentOverviewPartial.cshtml
@model LB2.Models.Студенты
<div class="row">
    <div class="col-md-4"> @Model.Фамилия @Model.Имя @Model.Отчество
   ( @Html.Action("GraduationDate",new { studentID=Model.ID_студента }))
    </div>
    <div class="col-md-2"> @Model.Дата_рождения </div>
    @if (User.Identity.IsAuthenticated)
    {
    <div class="col-md-2"> @Html.ActionLink("Подробнее", "StudentDetails", "LB2", new { personId = Model.ID_студента }, null) </div>
        if (User.IsInRole("Admin"))
        {
    <div class="col-md-2"> @Html.ActionLink("Редактировать", "EditStudent", "LB2", new { studentID = Model.ID_студента }, null) </div>
    <div class="col-md-2"> @Html.ActionLink("Удалить", "DeleteStudent", "LB2", new { studentID = Model.ID_студента }, null) </div>
        }
    }
</div>